### ISSUE TITLE
Setting input_method to 'fixed' causes a bug

### ISSUE THREAD

**Issue by m-bain** [kyamagu/bbox-annotator#11]
input_method: 'fixed'
After the reset button is pressed and the clear_all() function is called, the user is no longer able to draw boxes.

**Comment by m-bain** [comment]
Found the solution. 
Bug here:
` <input id="reset_button" type="reset" />`
AMT has its own definition for _type "reset"_. Change this line to:
`<input id="reset_button" type="button" value="Reset" />`

**Comment by kyamagu** [comment]
@maxhbain Thanks, PR #12 fixed
