### ISSUE TITLE
implement crosshair covering full image

### ISSUE THREAD

**Issue by basvroeg** [kyamagu/bbox-annotator#14]
Hi,

thanks for the nice tool, am planning to use it for our image annotation on Mturk as well. However, there is a small challenge I could not yet solve...

For our images, we would like to use a crosshair that extends over the whole image, such as https://codepen.io/anon/pen/LXZjwX, https://gist.github.com/salembeats/6f9aeb3f3438647a0f53715ae2e904bc or http://jsfiddle.net/WmZ44/1/. Reason behind is, is that objects tend to be somewhat large, and this is a great help in properly selecting the starting point of the bounding box.

However, tried to implement the latter link today, as being the most simple, and kinda equivalent to the former.  After struggling for hours also understood some more of Javascript and Jqueri, the code seems fine and correct to my understanding, but the system does not work within the mTurk sandbox. 

could you provide some clarification here? for referencing, the version of the code I created/used today is attached:
[annotatescript.txt](https://github.com/kyamagu/bbox-annotator/files/2567360/annotatescript.txt)

your help / support is kindly appreciated!

ps: to add on this, //test3c seems to me the location where the relevant javascript code should be added...

**Comment by basvroeg** [comment]
to add on this, //test3c seems to me the location where the relevant javascript code should be added...

**Comment by kyamagu** [comment]
@basvroeg Editing compiled coffeescript is not a good approach. The latest commit adds support for horizontal/vertical guide lines. Get the latest code.

**Comment by basvroeg** [comment]
thanks a lot for your support! My JavaScript knowledge is not that great, let alone Coffeescript....
