### ISSUE TITLE
Detect elements from DOM browser

### ISSUE THREAD

**Issue by ankitaggarwal-trantor** [kyamagu/bbox-annotator#15]
Hi Kyamagu,

Thank you for making this annotator as its very useful to solve some real world problems. 

But my problem is a bit different as I am looking to detect elements on web page and draw bounding boxes around them. For example: there is a form on web page and i want to detect input fields and draw bounding boxes around them.
As I explored your library, it requires the image URL and it only draws on images. Is there anything in this to achieve my requirement ?

Regards,
Ankit Aggarwal

**Comment by kyamagu** [comment]
@ankitaggarwal-trantor This is an image annotation tool, not a generic web page annotator. You can use other tools like [this](https://github.com/openannotation/annotator/).
