### ISSUE TITLE
Is it possible to show bounding boxes stored in a JSON file?

### ISSUE THREAD

**Issue by tofighi** [kyamagu/bbox-annotator#16]
I am wondering if it is possible to show bounding boxes on the image that are stored in a JSON file.

**Comment by kyamagu** [comment]
@tofighi Check the `add_entry()` method.
https://github.com/kyamagu/bbox-annotator/blob/master/bbox_annotator.coffee#L228

```javascript
editor.add_entry({
    "top": 0,
    "left": 0,
    "width": 100,
    "height": 100,
    "label", "object"
})
```

**Comment by tofighi** [comment]
Thanks but it does not work for me, probably because I am not using the right way to call the function. Let's say I am going to change the behavior of the reset button in your demo example as follows:

```javascript
  // Initialize the reset button.
  $("#reset_button").click(function(e) {
    annotator.clear_all();
  })
```


I would like to click on the reset button and the following label is desired to be added to the figure:

```javascript
{
    "top": 0,
    "left": 0,
    "width": 100,
    "height": 100,
    "label", "object"
}
```

The following solution will not work, could you please help?

```javascript
  // Initialize the reset button.
  $("#reset_button").click(function(e) {
    annotator.add_entry({
    "top": 0,
    "left": 0,
    "width": 100,
    "height": 100,
    "label", "object"
     })
  })
```

**Comment by kyamagu** [comment]
@tofighi You need to clear all first then add a desired one.

```javascript
  // Initialize the reset button.
  $("#reset_button").click(function(e) {
    annotator.clear_all();
    annotator.add_entry({
      "top": 10,
      "left": 10,
      "width": 100,
      "height": 100,
      "label": "object"
    });
  });
  // Force initialization here by clicking the reset once at the beginning.
  $("#reset_button").click();
```

**Comment by tofighi** [comment]
@kyamagu Worked perfectly.
