### ISSUE TITLE
Multiple images in one MTurk HIT?

### ISSUE THREAD

**Issue by brentonpeterson** [kyamagu/bbox-annotator#5]
This is a dumb question, because I don't know javascript.  

I've been using your Mturk html example for awhile.  But I'd like to have multiple distinct images on a single HIT or screen, so that a worker can annotate, say, 5 images.  

Which portion of the script would I need to repeat to display multiple images and allow an annotation on each?  Thanks in advance!

**Comment by kyamagu** [comment]
@brentonpeterson You can simply create multiple block elements with different id:

```html
<div id="bbox_annotator0"></div>
<input id="annotation_data0" name="annotation_data0" type="hidden" />
<div id="bbox_annotator1"></div>
<input id="annotation_data1" name="annotation_data1" type="hidden" />
```
```
<script type="text/javascript">
$(document).ready(function() {
  var editor0 = new BBoxAnnotator({
    url: "/url/to/image0.jpg",
    id: "#bbox_annotator0"
  });
  var editor1 = new BBoxAnnotator({
    url: "/url/to/image1.jpg",
    id: "#bbox_annotator1"
  });
});
</script>
```

**Comment by brentonpeterson** [comment]
That worked brilliantly, after a bit of trial and error.  Thanks a lot!
