### ISSUE TITLE
Reatain bounding box

### ISSUE THREAD

**Issue by defaultcute12** [kyamagu/bbox-annotator#7]
Is there any way we can retain the bounding box for that particular image 
i.e whenever we open the image we see the bounding boxes drawn previously.
right now annotation data can be saved in db, but drawn rectangles go after refresh

**Comment by kyamagu** [comment]
@defaultcute12 You can use `add_entry()` method to append a box. See https://github.com/kyamagu/bbox-annotator/blob/master/bbox_annotator.coffee#L218

**Comment by defaultcute12** [comment]
Thanks a lot, I made it using nodejs screenshot plugin. 
Thanks a lot for the help, I really appreciate.
